# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inPrint',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
