# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dateAdded',
        ),
    ]
