# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField(max_length=1000)),
                ('product_weight', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('product_cost', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
