# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='productCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_cost',
            new_name='productCost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='productDescription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='productName',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='productPrice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_weight',
            new_name='productWeight',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
