# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usernameApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Username',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user',
        ),
    ]
