# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='interest',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(to='userApp.Interest'),
        ),
    ]
