# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_test', '0002_auto_20170621_1832'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
